steps:
  - name: "bazel test opt"
    command: bazel test -c opt --test_output=all //...
    agents:
      queue: dev
    plugins:
      https://github.com/iotaledger/docker-buildkite-plugin#release-v1.4.0:
        image: "iotacafe/iota-buildenv"
        always-pull: true
        mounts:
          - /conf:/conf
          - /cache:/cache
  - name: "bazel test debug"
    command: bazel test -c dbg --test_output=all //...
    agents:
      queue: dev
    plugins:
      https://github.com/iotaledger/docker-buildkite-plugin#release-v1.4.0:
        image: "iotacafe/iota-buildenv"
        always-pull: true
        mounts:
          - /conf:/conf
          - /cache:/cache
  - name: "bazel test bootlin x86_64 toolchains"
    command: bazel test --crosstool_top=@iota_toolchains//tools/x86-64-core-i7--glibc--bleeding-edge-2018.07-1:toolchain --cpu=x86_64 --host_crosstool_top=@bazel_tools//tools/cpp:toolchain  //...
    agents:
      queue: dev
    plugins:
      https://github.com/iotaledger/docker-buildkite-plugin#release-v1.4.0:
        image: "iotacafe/iota-buildenv"
        always-pull: true
        mounts:
          - /conf:/conf
          - /cache:/cache
