steps:
  - name: api-build-and-deploy-staging
    command:
      - |
        rm -rf ci-pipelines && git clone https://github.com/iotaledger/ci-pipelines.git
        npm i -g --unsafe-perm now@16.3.0
        cp ci-pipelines/$BUILDKITE_PIPELINE_SLUG/api/src/data/config.staging.json api/src/data/
        cp ci-pipelines/$BUILDKITE_PIPELINE_SLUG/api/now.staging.json api/now.json
        sed -i.bak s#DOCS-STAGING-AWS-ACCESS-KEY-ID#\$DOCS_STAGING_AWS_ACCESS_KEY_ID#g api/src/data/config.staging.json
        sed -i.bak s#DOCS-STAGING-AWS-SECRET-ACCESS-KEY#\$DOCS_STAGING_AWS_SECRET_ACCESS_KEY#g api/src/data/config.staging.json
        sed -i.bak s#DOCS-STAGING-SOLR-ENDPOINT#\$DOCS_STAGING_SOLR_ENDPOINT#g api/src/data/config.staging.json
        sed -i.bak s#DOCS-STAGING-SOLR-CORE#\$DOCS_STAGING_SOLR_CORE#g api/src/data/config.staging.json
        sed -i.bak s#DOCS-STAGING-SOLR-AUTHORIZATION#\$DOCS_STAGING_SOLR_AUTHORIZATION#g api/src/data/config.staging.json
        rm -rf ci-pipelines
        cd api
        now --platform-version 1 --token \$ZEIT_TOKEN --team iota deploy -e CONFIG_ID=staging --build-env CONFIG_ID=staging --build-env SEARCH_ENDPOINT=\$DOCS_STAGING_SOLR_ENDPOINT --build-env SEARCH_CORE=document-core-staging --build-env SEARCH_AUTHORIZATION=\$DOCS_STAGING_SOLR_AUTHORIZATION --force --docker -n documentation-api -m BK_JOB_ID=$BUILDKITE_JOB_ID
        NOW_SH_DEPLOYMENT_ID=$(now --platform-version 1 --token \$ZEIT_TOKEN --team iota ls -m BK_JOB_ID=$BUILDKITE_JOB_ID | grep documentation-api | awk {'print \$2'})
        now --platform-version 1 --token \$ZEIT_TOKEN --team iota alias \$NOW_SH_DEPLOYMENT_ID docs-api.iota.works
        now --platform-version 1 --token \$ZEIT_TOKEN --team iota logs \$NOW_SH_DEPLOYMENT_ID
    plugins:
       https://github.com/iotaledger/docker-buildkite-plugin#release-v2.0.0:
         image: "node:12.16-stretch"
         environment:
          - ZEIT_TOKEN
          - DOCS_STAGING_AWS_ACCESS_KEY_ID
          - DOCS_STAGING_AWS_SECRET_ACCESS_KEY
          - DOCS_STAGING_SOLR_ENDPOINT
          - DOCS_STAGING_SOLR_CORE
          - DOCS_STAGING_SOLR_AUTHORIZATION
    agents:
      queue: ops

  - name: web-build-and-deploy-staging
    command:
      - |
        rm -rf docs && mkdir -p docs
        rm -rf ci-pipelines && git clone https://github.com/iotaledger/ci-pipelines.git
        if [ -z "$DOCS_MARKDOWN_BUILDKITE_BUILD_ID" ]; then
          echo Pass DOCS_MARKDOWN_BUILDKITE_BUILD_ID as the documentation-markdown build id
          exit 1
        else
          echo Downloading documentation markdown from build $DOCS_MARKDOWN_BUILDKITE_BUILD_ID
          buildkite-agent artifact download documentation-markdown.tgz docs/ --build $DOCS_MARKDOWN_BUILDKITE_BUILD_ID
        fi
        cd docs && tar xvfz documentation-markdown.tgz && rm documentation-markdown.tgz && cd ../
        npm i -g --unsafe-perm now@16.3.0
        cp ci-pipelines/$BUILDKITE_PIPELINE_SLUG/web/src/config.staging.json src/config.staging.json
        cp ci-pipelines/$BUILDKITE_PIPELINE_SLUG/web/now.staging.json now.json
        rm -rf ci-pipelines
        rm .gitignore
        now --platform-version 1 --token \$ZEIT_TOKEN --team iota deploy -e CONFIG_ID=staging --build-env CONFIG_ID=staging --build-env SEARCH_ENDPOINT=\$DOCS_STAGING_SOLR_ENDPOINT --build-env SEARCH_CORE=document-core-staging --build-env SEARCH_AUTHORIZATION=\$DOCS_STAGING_SOLR_AUTHORIZATION --force --docker -n documentation-web -m BK_JOB_ID=$BUILDKITE_JOB_ID
        NOW_SH_DEPLOYMENT_ID=$(now --platform-version 1 --token \$ZEIT_TOKEN --team iota ls -m BK_JOB_ID=$BUILDKITE_JOB_ID | grep documentation-web | awk {'print \$2'})
        now --platform-version 1 --token \$ZEIT_TOKEN --team iota alias \$NOW_SH_DEPLOYMENT_ID docs.iota.works
        now --platform-version 1 --token \$ZEIT_TOKEN --team iota logs \$NOW_SH_DEPLOYMENT_ID
    plugins:
       https://github.com/iotaledger/docker-buildkite-plugin#release-v2.0.0:
         image: "node:12.16-stretch"
         mount-buildkite-agent: true
         environment:
          - ZEIT_TOKEN
          - DOCS_MARKDOWN_BUILDKITE_BUILD_ID
    agents:
      queue: ops

  - block: "Deploy LIVE"
    prompt: "Deploy this build to docs.iota.org and docs-api.iota.org?"

  - name: api-build-and-deploy-prod
    command:
      - |
        npm i -g --unsafe-perm now@16.3.0
        rm -rf ci-pipelines && git clone https://github.com/iotaledger/ci-pipelines.git
        cp ci-pipelines/$BUILDKITE_PIPELINE_SLUG/api/src/data/config.prod.json api/src/data/
        cp ci-pipelines/$BUILDKITE_PIPELINE_SLUG/api/now.prod.json api/now.json
        sed -i.bak s#DOCS-PROD-AWS-ACCESS-KEY-ID#\$DOCS_PROD_AWS_ACCESS_KEY_ID#g api/src/data/config.prod.json
        sed -i.bak s#DOCS-PROD-AWS-SECRET-ACCESS-KEY#\$DOCS_PROD_AWS_SECRET_ACCESS_KEY#g api/src/data/config.prod.json
        sed -i.bak s#DOCS-PROD-SOLR-ENDPOINT#\$DOCS_PROD_SOLR_ENDPOINT#g api/src/data/config.staging.json
        sed -i.bak s#DOCS-PROD-SOLR-CORE#\$DOCS_PROD_SOLR_CORE#g api/src/data/config.staging.json
        sed -i.bak s#DOCS-PROD-SOLR-AUTHORIZATION#\$DOCS_PROD_SOLR_AUTHORIZATION#g api/src/data/config.staging.json
        rm -rf ci-pipelines
        cd api
        now --platform-version 1 --token \$ZEIT_TOKEN --team iota deploy -e CONFIG_ID=prod --build-env CONFIG_ID=prod --build-env SEARCH_ENDPOINT=\$DOCS_PROD_SOLR_ENDPOINT --build-env SEARCH_CORE=document-core-prod --build-env SEARCH_AUTHORIZATION=$DOCS_PROD_SOLR_AUTHORIZATION --force --docker -n documentation-api -m BK_JOB_ID=$BUILDKITE_JOB_ID
        NOW_SH_DEPLOYMENT_ID=$(now --platform-version 1 --token \$ZEIT_TOKEN --team iota ls -m BK_JOB_ID=$BUILDKITE_JOB_ID | grep documentation-api | awk {'print \$2'})
        now --platform-version 1 --token \$ZEIT_TOKEN --team iota alias \$NOW_SH_DEPLOYMENT_ID docs-api.iota.org
        now --platform-version 1 --token \$ZEIT_TOKEN --team iota logs \$NOW_SH_DEPLOYMENT_ID
    plugins:
       https://github.com/iotaledger/docker-buildkite-plugin#release-v2.0.0:
         image: "node:12.16-stretch"
         environment:
          - ZEIT_TOKEN
          - DOCS_PROD_AWS_ACCESS_KEY_ID
          - DOCS_PROD_AWS_SECRET_ACCESS_KEY
          - DOCS_PROD_SOLR_ENDPOINT
          - DOCS_PROD_SOLR_CORE
          - DOCS_PROD_SOLR_AUTHORIZATION
    agents:
      queue: ops

  - name: web-build-and-deploy-prod
    command:
      - |
        rm -rf docs && mkdir -p docs
        rm -rf ci-pipelines && git clone https://github.com/iotaledger/ci-pipelines.git
        if [ -z "$DOCS_MARKDOWN_BUILDKITE_BUILD_ID" ]; then
          echo Pass DOCS_MARKDOWN_BUILDKITE_BUILD_ID as the documentation-markdown build id
          exit 1
        else
          echo Downloading documentation markdown from build $DOCS_MARKDOWN_BUILDKITE_BUILD_ID
          buildkite-agent artifact download documentation-markdown.tgz docs/ --build $DOCS_MARKDOWN_BUILDKITE_BUILD_ID
        fi
        cd docs && tar xvfz documentation-markdown.tgz && rm documentation-markdown.tgz && cd ../

        npm i -g --unsafe-perm now@16.3.0
        cp ci-pipelines/$BUILDKITE_PIPELINE_SLUG/web/src/config.prod.json src/config.prod.json
        cp ci-pipelines/$BUILDKITE_PIPELINE_SLUG/web/now.prod.json now.json
        rm -rf ci-pipelines
        rm .gitignore
        now --platform-version 1 --token \$ZEIT_TOKEN --team iota deploy -e CONFIG_ID=prod --build-env CONFIG_ID=prod --force --docker -n documentation-web -m BK_JOB_ID=$BUILDKITE_JOB_ID
        NOW_SH_DEPLOYMENT_ID=$(now --platform-version 1 --token \$ZEIT_TOKEN --team iota ls -m BK_JOB_ID=$BUILDKITE_JOB_ID | grep documentation-web | awk {'print \$2'})
        now --platform-version 1 --token \$ZEIT_TOKEN --team iota alias \$NOW_SH_DEPLOYMENT_ID docs.iota.org
        now --platform-version 1 --token \$ZEIT_TOKEN --team iota logs \$NOW_SH_DEPLOYMENT_ID
    plugins:
       https://github.com/iotaledger/docker-buildkite-plugin#release-v2.0.0:
         image: "node:12.16-stretch"
         mount-buildkite-agent: true
         environment:
          - ZEIT_TOKEN
          - DOCS_MARKDOWN_BUILDKITE_BUILD_ID
    agents:
      queue: ops
